# Generated by Django 6.1.1 on 2026-09-26 14:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_student_house'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffLeave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('casual', 'Casual'), ('sick', 'Sick'), ('earned', 'Earned')], max_length=8)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('half_day', models.BooleanField(default=False)),
                ('days', models.DecimalField(decimal_places=1, max_digits=4)),
                ('reason', models.CharField(max_length=400)),
                ('certificate', models.FileField(blank=True, upload_to='staff-leave/%Y/%m/')),
                ('certificate_name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=200)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_leaves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-from_date'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(blank=True, max_length=30)),
                ('designation', models.CharField(blank=True, help_text='e.g. Mathematics', max_length=80)),
                ('joined_on', models.DateField(blank=True, null=True)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('school', 'user'), name='uniq_staff_profile')],
            },
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, help_text='e.g. on leave', max_length=60)),
                ('assigned_at', models.DateTimeField()),
                ('handover_note', models.TextField(blank=True, max_length=1000)),
                ('handover_at', models.DateTimeField(blank=True, null=True)),
                ('absent_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='academics.timetableslot')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'slot__period'],
                'constraints': [models.UniqueConstraint(fields=('date', 'slot'), name='uniq_substitution_slot')],
            },
        ),
    ]
