# Generated by Django 6.1.1 on 2026-09-26 16:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_student_house'),
        ('staff', '0002_staffattendance'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='e.g. Physics (PGT)', max_length=80)),
                ('kind', models.CharField(choices=[('teaching', 'Teaching'), ('support', 'Support')], default='teaching', max_length=8)),
                ('positions', models.PositiveSmallIntegerField(default=1)),
                ('applicants', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('filled', 'Filled'), ('closed', 'Closed')], default='open', max_length=8)),
                ('opened_on', models.DateField()),
                ('closes_on', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.subject')),
            ],
            options={
                'ordering': ['opened_on'],
            },
        ),
    ]
