# Generated by Django 5.2.18 on 2026-10-10 07:51

import django.contrib.postgres.fields
import django.db.models.deletion
import eduflow.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_term_room_integrity_and_rls'),
        ('people', '0004_enrollment_record_key'),
        ('tenancy', '0003_school_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=10000)),
                ('audiences', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('staff', 'Staff'), ('parents', 'Parents'), ('students', 'Students')], max_length=16), size=3)),
                ('pinned', models.BooleanField(default=False)),
                ('requires_acknowledgement', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.section')),
            ],
            options={
                'db_table': 'communication_announcement',
            },
        ),
        migrations.CreateModel(
            name='Acknowledgement',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='communication.announcement')),
            ],
            options={
                'db_table': 'communication_acknowledgement',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementResponse',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=2000)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='communication.announcement')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'communication_announcement_response',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('transport', 'Transport'), ('academics', 'Academics'), ('fees', 'Fees'), ('facilities', 'Facilities'), ('staff', 'Staff'), ('food', 'Food')], max_length=16)),
                ('text', models.CharField(max_length=3000)),
                ('sentiment', models.CharField(choices=[('negative', 'Negative'), ('neutral', 'Neutral'), ('positive', 'Positive')], max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('resolution', models.CharField(blank=True, max_length=2000)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='people.student')),
            ],
            options={
                'db_table': 'communication_complaint',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('parent_class_teacher', 'Parent and class teacher'), ('parent_subject_teacher', 'Parent and subject teacher'), ('student_teacher', 'Student and teacher')], max_length=32)),
                ('awaiting_reply_since', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='threads', to='people.guardian')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='threads', to='people.staffprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='threads', to='people.student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.subject')),
            ],
            options={
                'db_table': 'communication_thread',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('from_staff', models.BooleanField()),
                ('text', models.TextField(max_length=5000)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('reply_seconds', models.PositiveIntegerField(blank=True, help_text="For a staff reply: seconds since the family's message it answers.", null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communication.thread')),
            ],
            options={
                'db_table': 'communication_message',
                'ordering': ['at'],
            },
        ),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.CheckConstraint(condition=models.Q(('audiences__contained_by', ['staff', 'parents', 'students']), models.Q(('audiences', []), _negated=True)), name='communication_audiences_check'),
        ),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='communication_announcement_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='acknowledgement',
            constraint=models.UniqueConstraint(fields=('announcement', 'member'), name='communication_ack_uniq'),
        ),
        migrations.AddConstraint(
            model_name='acknowledgement',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='communication_acknowledgement_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='announcementresponse',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='communication_announcement_response_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'resolved'), _negated=True), ('resolved_at__isnull', False), _connector='OR'), name='communication_resolved_check'),
        ),
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='communication_complaint_id_school_uniq'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['school', 'awaiting_reply_since'], name='communication_awaiting_idx'),
        ),
        migrations.AddConstraint(
            model_name='thread',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('guardian__isnull', True), ('kind', 'student_teacher')), models.Q(models.Q(('kind', 'student_teacher'), _negated=True), ('guardian__isnull', False)), _connector='OR'), name='communication_thread_parties_check'),
        ),
        migrations.AddConstraint(
            model_name='thread',
            constraint=models.UniqueConstraint(fields=('kind', 'student', 'staff', 'guardian'), name='communication_thread_uniq', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='thread',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='communication_thread_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='communication_message_id_school_uniq'),
        ),
    ]
