# Generated by Django 6.1.1 on 2026-09-26 16:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_preferences'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, max_length=60)),
                ('module', models.CharField(blank=True, db_index=True, max_length=30)),
                ('target_type', models.CharField(blank=True, max_length=40)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('device', models.CharField(blank=True, max_length=200)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'module', '-created_at'], name='accounts_au_school__d044a8_idx')],
            },
        ),
    ]
