# Generated by Django 5.2.18 on 2026-10-08 14:23

import eduflow.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('school_id', models.UUIDField(blank=True, help_text='Null for platform and sign-in events.', null=True)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=64)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('denied', 'Denied')], default='success', max_length=8)),
                ('target_type', models.CharField(blank=True, max_length=48)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('request_id', models.CharField(blank=True, max_length=128)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'audit_event',
                'ordering': ('-id',),
                'indexes': [models.Index(fields=['school_id', '-occurred_at'], name='audit_event_school_time_idx'), models.Index(fields=['school_id', 'target_type', 'target_id'], name='audit_event_target_idx'), models.Index(fields=['actor_id', '-occurred_at'], name='audit_event_actor_time_idx'), models.Index(fields=['action', '-occurred_at'], name='audit_event_action_time_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('outcome__in', ['success', 'failure', 'denied'])), name='audit_event_outcome_check')],
            },
        ),
    ]
