# Generated by Django 5.2.18 on 2026-10-10 08:17

import datetime
import django.contrib.postgres.fields
import django.db.models.deletion
import eduflow.core.ids
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0003_school_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('rule', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('domain', models.CharField(choices=[('students', 'Students'), ('staff', 'Staff'), ('operations', 'Operations'), ('finance', 'Finance')], max_length=16)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('watch', 'Watch')], max_length=16)),
                ('headline', models.CharField(max_length=300)),
                ('why', models.CharField(max_length=1000)),
                ('owner', models.CharField(max_length=100)),
                ('escalates_to', models.CharField(max_length=150)),
                ('items', models.JSONField(default=list)),
                ('staff_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, help_text='Staff an item is about or owned by.', size=None)),
                ('section_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('occurrences', models.PositiveIntegerField(default=1)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('auto_resolved', models.BooleanField(default=False)),
                ('resolution_note', models.CharField(blank=True, max_length=500)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'monitoring_alert',
                'indexes': [models.Index(fields=['school', 'status'], name='monitoring_alert_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'resolved'), _negated=True), fields=('school', 'rule'), name='monitoring_one_live_alert_per_rule'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'resolved'), _negated=True), ('resolved_at__isnull', False), _connector='OR'), name='monitoring_resolved_check'), models.UniqueConstraint(fields=('id', 'school'), name='monitoring_alert_id_school_uniq')],
            },
        ),
        migrations.CreateModel(
            name='MonitoringSettings',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('attendance_risk', models.DecimalField(decimal_places=2, default=Decimal('0.75'), max_digits=3)),
                ('attendance_window_days', models.PositiveSmallIntegerField(default=60)),
                ('slip_drop', models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=3)),
                ('slip_recent_days', models.PositiveSmallIntegerField(default=15)),
                ('absent_streak_days', models.PositiveSmallIntegerField(default=3)),
                ('marks_drop', models.DecimalField(decimal_places=2, default=Decimal('12'), max_digits=5)),
                ('behaviour_incidents', models.PositiveSmallIntegerField(default=3)),
                ('fee_overdue', models.DecimalField(decimal_places=2, default=Decimal('10000'), max_digits=12)),
                ('reply_hours', models.PositiveSmallIntegerField(default=24)),
                ('unreviewed_submissions', models.PositiveSmallIntegerField(default=25)),
                ('late_arrivals', models.PositiveSmallIntegerField(default=5)),
                ('late_window_days', models.PositiveSmallIntegerField(default=30)),
                ('approval_hours', models.PositiveSmallIntegerField(default=24)),
                ('bus_delay_minutes', models.PositiveSmallIntegerField(default=10)),
                ('register_by', models.TimeField(default=datetime.time(8, 15))),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'monitoring_settings',
                'constraints': [models.UniqueConstraint(fields=('school',), name='monitoring_settings_school_uniq'), models.CheckConstraint(condition=models.Q(('attendance_risk__gt', 0), ('attendance_risk__lte', 1), ('slip_drop__gt', 0), ('slip_drop__lte', 1)), name='monitoring_ratio_check')],
            },
        ),
    ]
