# Generated by Django 5.2.18 on 2026-10-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_tenant_integrity_and_rls'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.UniqueConstraint(fields=('id', 'staff', 'section', 'subject', 'school'), name='people_assignment_slot_key_uniq'),
        ),
    ]
