# Generated by Django 5.2.18 on 2026-10-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_assignment_slot_key'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('id', 'student', 'section', 'school'), name='people_enrollment_record_key_uniq'),
        ),
    ]
