# Generated by Django 5.2.18 on 2026-10-08 14:23

import django.db.models.deletion
import eduflow.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(help_text='Short public code used to find the school.', max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('rbac_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenancy_school',
                'constraints': [models.CheckConstraint(condition=models.Q(('code__regex', '^[a-z0-9][a-z0-9-]{1,31}$')), name='tenancy_school_code_check')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='tenancy.school')),
            ],
            options={
                'db_table': 'tenancy_membership',
                'indexes': [models.Index(fields=['user', 'is_active'], name='tenancy_membership_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'user'), name='tenancy_membership_school_user_uniq'), models.UniqueConstraint(fields=('id', 'school'), name='tenancy_membership_id_school_uniq')],
            },
        ),
    ]
