# Generated by Django 5.2.18 on 2026-10-10 06:11

import django.db.models.deletion
import eduflow.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_term_room_integrity_and_rls'),
        ('people', '0004_enrollment_record_key'),
        ('tenancy', '0003_school_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePlan',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.academicyear')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'fees_plan',
            },
        ),
        migrations.CreateModel(
            name='Instalment',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=60)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalments', to='fees.feeplan')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'fees_instalment',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode', models.CharField(choices=[('upi', 'UPI'), ('card', 'Card'), ('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('cheque', 'Cheque')], max_length=16)),
                ('reference', models.CharField(blank=True, help_text='UPI / card / cheque reference.', max_length=100)),
                ('paid_on', models.DateField()),
                ('receipt_number', models.CharField(max_length=32)),
                ('client_key', models.CharField(blank=True, max_length=64)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_payments', to='people.student')),
            ],
            options={
                'db_table': 'fees_payment',
            },
        ),
        migrations.CreateModel(
            name='ReceiptCounter',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('last', models.PositiveIntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'fees_receipt_counter',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='fees.payment')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'fees_refund',
            },
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('scholarship_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('scholarship_note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='fees.feeplan')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fees', to='people.student')),
            ],
            options={
                'db_table': 'fees_student_fee',
            },
        ),
        migrations.AddConstraint(
            model_name='feeplan',
            constraint=models.UniqueConstraint(fields=('academic_year', 'name'), name='fees_plan_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='feeplan',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='fees_plan_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='instalment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='fees_instalment_amount_check'),
        ),
        migrations.AddConstraint(
            model_name='instalment',
            constraint=models.UniqueConstraint(fields=('plan', 'label'), name='fees_instalment_label_uniq'),
        ),
        migrations.AddConstraint(
            model_name='instalment',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='fees_instalment_id_school_uniq'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['school', 'paid_on'], name='fees_payment_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='fees_payment_amount_check'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('mode__in', ['upi', 'card', 'cash', 'bank_transfer', 'cheque'])), name='fees_payment_mode_check'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('school', 'receipt_number'), name='fees_receipt_uniq'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('client_key', ''), _negated=True), fields=('school', 'client_key'), name='fees_payment_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='fees_payment_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='receiptcounter',
            constraint=models.UniqueConstraint(fields=('school',), name='fees_receipt_counter_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='fees_refund_amount_check'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='fees_refund_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='studentfee',
            constraint=models.UniqueConstraint(fields=('student', 'plan'), name='fees_student_plan_uniq'),
        ),
        migrations.AddConstraint(
            model_name='studentfee',
            constraint=models.CheckConstraint(condition=models.Q(('scholarship_percent__gte', 0), ('scholarship_percent__lte', 100)), name='fees_scholarship_range_check'),
        ),
        migrations.AddConstraint(
            model_name='studentfee',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='fees_student_fee_id_school_uniq'),
        ),
    ]
