# Generated by Django 5.2.18 on 2026-10-10 06:56

import django.db.models.deletion
import eduflow.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0003_school_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('sku', models.CharField(max_length=40)),
                ('unit', models.CharField(default='unit', max_length=20)),
                ('category', models.CharField(blank=True, max_length=60)),
                ('reorder_level', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'inventory_item',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'inventory_purchase_order',
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.item')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.purchaseorder')),
            ],
            options={
                'db_table': 'inventory_order_line',
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('received_on', models.DateField()),
                ('note', models.CharField(blank=True, max_length=300)),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='inventory.purchaseorder')),
            ],
            options={
                'db_table': 'inventory_goods_receipt',
            },
        ),
        migrations.CreateModel(
            name='ReceiptLine',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.orderline')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.goodsreceipt')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'inventory_receipt_line',
            },
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('justification', models.CharField(max_length=1000)),
                ('estimated_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'inventory_requisition',
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='inventory.requisition'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('receipt', 'Receipt'), ('issue', 'Issue'), ('adjustment', 'Adjustment')], max_length=16)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Signed: receipts +, issues -.', max_digits=12)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('issued_to', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goods_receipt_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.receiptline')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.item')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'inventory_stock_movement',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tax_id', models.CharField(blank=True, help_text='GSTIN or other tax registration.', max_length=32)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'inventory_vendor',
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='inventory.vendor'),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(blank=True, max_length=60)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('in_use', 'In use'), ('in_store', 'In store'), ('in_repair', 'In repair'), ('disposed', 'Disposed')], default='in_use', max_length=16)),
                ('disposed_on', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.vendor')),
            ],
            options={
                'db_table': 'inventory_asset',
            },
        ),
        migrations.CreateModel(
            name='VendorInvoice',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=16)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='inventory.purchaseorder')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'inventory_vendor_invoice',
            },
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('school', 'sku'), name='inventory_item_sku_uniq'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='inventory_item_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inventory_line_qty_check'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='inventory_line_price_check'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__gte', 0), ('received_quantity__lte', models.F('quantity'))), name='inventory_line_received_check'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='inventory_order_line_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceipt',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='inventory_goods_receipt_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='receiptline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inventory_receipt_qty_check'),
        ),
        migrations.AddConstraint(
            model_name='receiptline',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='inventory_receipt_line_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='requisition',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_total__gt', 0)), name='inventory_requisition_total_check'),
        ),
        migrations.AddConstraint(
            model_name='requisition',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='inventory_requisition_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'receipt'), ('quantity__gt', 0)), models.Q(('kind', 'issue'), ('quantity__lt', 0)), models.Q(('kind', 'adjustment'), models.Q(('quantity', 0), _negated=True)), _connector='OR'), name='inventory_movement_sign_check'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='inventory_stock_movement_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='inventory_vendor_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='inventory_vendor_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('school', 'number'), name='inventory_po_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='inventory_purchase_order_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('school', 'tag'), name='inventory_asset_tag_uniq'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'disposed'), _negated=True), ('disposed_on__isnull', False), _connector='OR'), name='inventory_disposed_check'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='inventory_asset_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='vendorinvoice',
            constraint=models.UniqueConstraint(fields=('order', 'number'), name='inventory_invoice_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='vendorinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='inventory_invoice_amount_check'),
        ),
        migrations.AddConstraint(
            model_name='vendorinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'unpaid'), ('paid_on__isnull', False), _connector='OR'), name='inventory_invoice_paid_check'),
        ),
        migrations.AddConstraint(
            model_name='vendorinvoice',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='inventory_vendor_invoice_id_school_uniq'),
        ),
    ]
