# Generated by Django 5.2.18 on 2026-10-08 16:02

import django.contrib.postgres.constraints
import django.db.models.deletion
import django.db.models.functions.text
import eduflow.academics.models
import eduflow.core.ids
import django.contrib.postgres.operations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0003_school_profile'),
    ]

    operations = [
        # The no-overlap exclusion constraint on academic years compares school_id with '=' in a GiST index.
        django.contrib.postgres.operations.BtreeGistExtension(),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='For example "2026-27".', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('closed', 'Closed')], default='planned', max_length=16)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'academics_academic_year',
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='IN', max_length=2)),
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.SlugField(max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'academics_campus',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'academics_department',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('code', models.SlugField(max_length=32)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'academics_grade',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='For example "A" or "Rose".', max_length=50)),
                ('code', models.SlugField(max_length=32)),
                ('capacity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='academics.academicyear')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='academics.campus')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='academics.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'academics_section',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=32)),
                ('short_name', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(choices=[('core', 'Core'), ('elective', 'Elective'), ('language', 'Language'), ('co_curricular', 'Co-curricular'), ('other', 'Other')], default='core', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academics.department')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'academics_subject',
            },
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['school', '-start_date'], name='academics_year_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='academics_academic_year_dates_check'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.CheckConstraint(condition=models.Q(('is_current', False), ('status', 'active'), _connector='OR'), name='academics_academic_year_current_is_active_check'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('school',), name='academics_academic_year_one_current_uniq'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(models.F('school'), django.db.models.functions.text.Lower('name'), name='academics_academic_year_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('school', '='), (eduflow.academics.models.DateRange('start_date', 'end_date', models.Value('[]')), '&&')], name='academics_academic_year_no_overlap'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='academics_academic_year_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='campus',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='academics_campus_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='campus',
            constraint=models.UniqueConstraint(models.F('school'), django.db.models.functions.text.Lower('name'), name='academics_campus_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='campus',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='academics_campus_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='academics_department_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(models.F('school'), django.db.models.functions.text.Lower('name'), name='academics_department_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='academics_department_id_school_uniq'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['school', 'display_order'], name='academics_grade_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='academics_grade_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(models.F('school'), django.db.models.functions.text.Lower('name'), name='academics_grade_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='academics_grade_id_school_uniq'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['school', 'academic_year', 'grade'], name='academics_section_year_idx'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('academic_year', 'grade', 'code'), name='academics_section_year_grade_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(models.F('academic_year'), models.F('grade'), django.db.models.functions.text.Lower('name'), name='academics_section_year_grade_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__isnull', True), ('capacity__gt', 0), _connector='OR'), name='academics_section_capacity_positive_check'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='academics_section_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('id', 'academic_year', 'grade', 'school'), name='academics_section_full_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('id', 'academic_year', 'school'), name='academics_section_year_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='academics_subject_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(models.F('school'), django.db.models.functions.text.Lower('name'), name='academics_subject_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='academics_subject_id_school_uniq'),
        ),
    ]
