# Generated by Django 5.2.18 on 2026-10-09 09:06

import django.contrib.postgres.constraints
import django.db.models.deletion
import django.db.models.functions.text
import eduflow.academics.models
import eduflow.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_tenant_integrity_and_rls'),
        ('tenancy', '0003_school_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=32)),
                ('kind', models.CharField(choices=[('classroom', 'Classroom'), ('laboratory', 'Laboratory'), ('library', 'Library'), ('hall', 'Hall'), ('sports', 'Sports'), ('other', 'Other')], default='classroom', max_length=16)),
                ('capacity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='academics.campus')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'academics_room',
                'constraints': [models.UniqueConstraint(fields=('school', 'code'), name='academics_room_code_uniq'), models.UniqueConstraint(models.F('school'), models.F('campus'), django.db.models.functions.text.Lower('name'), name='academics_room_name_uniq', nulls_distinct=False), models.CheckConstraint(condition=models.Q(('capacity__isnull', True), ('capacity__gt', 0), _connector='OR'), name='academics_room_capacity_positive_check'), models.UniqueConstraint(fields=('id', 'school'), name='academics_room_id_school_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('code', models.SlugField(max_length=32)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='academics.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'academics_term',
                'indexes': [models.Index(fields=['school', 'academic_year', 'start_date'], name='academics_term_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='academics_term_dates_check'), models.UniqueConstraint(fields=('academic_year', 'code'), name='academics_term_code_uniq'), models.UniqueConstraint(models.F('academic_year'), django.db.models.functions.text.Lower('name'), name='academics_term_name_uniq'), django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('academic_year', '='), (eduflow.academics.models.DateRange('start_date', 'end_date', models.Value('[]')), '&&')], name='academics_term_no_overlap'), models.UniqueConstraint(fields=('id', 'school'), name='academics_term_id_school_uniq'), models.UniqueConstraint(fields=('id', 'academic_year', 'school'), name='academics_term_year_key_uniq')],
            },
        ),
    ]
