# Generated by Django 6.1.1 on 2026-09-18 20:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='The code people type to find the school.', max_length=16, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('short_name', models.CharField(blank=True, max_length=40)),
                ('kind', models.CharField(choices=[('school', 'School'), ('junior_college', 'Junior college'), ('college', 'College')], default='school', max_length=20)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=40)),
                ('primary_color', models.CharField(default='#2E5D4E', max_length=7)),
                ('accent_color', models.CharField(default='#B4763A', max_length=7)),
                ('logo_url', models.URLField(blank=True)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='tenancy.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
