# Generated by Django 5.2.18 on 2026-10-09 20:18

import django.db.models.deletion
import eduflow.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0004_enrollment_record_key'),
        ('tenancy', '0003_school_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('attendance', 'Attendance'), ('marks', 'Marks'), ('homework', 'Homework'), ('fees', 'Fees'), ('bus', 'Bus'), ('announcement', 'Announcement'), ('message', 'Message'), ('remark', 'Remark'), ('approval', 'Approval'), ('alert', 'Alert'), ('learning', 'Learning')], max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(blank=True, max_length=1000)),
                ('link_type', models.CharField(blank=True, help_text='The record this is about, e.g. homework.', max_length=40)),
                ('link_id', models.CharField(blank=True, max_length=64)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='people.student')),
            ],
            options={
                'db_table': 'notifications_notification',
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=8)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('suppressed', 'Suppressed')], default='queued', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('reason', models.CharField(blank=True, help_text='Why it was suppressed or failed.', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'notifications_delivery',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('attendance', 'Attendance'), ('marks', 'Marks'), ('homework', 'Homework'), ('fees', 'Fees'), ('bus', 'Bus'), ('announcement', 'Announcement'), ('message', 'Message'), ('remark', 'Remark'), ('approval', 'Approval'), ('alert', 'Alert'), ('learning', 'Learning')], max_length=16)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=8)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'notifications_preference',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['school', 'recipient', 'read_at'], name='notifications_inbox_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['attendance', 'marks', 'homework', 'fees', 'bus', 'announcement', 'message', 'remark', 'approval', 'alert', 'learning'])), name='notifications_kind_check'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='notifications_notification_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(fields=('notification', 'channel'), name='notifications_delivery_uniq'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['queued', 'sent', 'failed', 'suppressed'])), name='notifications_delivery_status_check'),
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.UniqueConstraint(fields=('membership', 'kind', 'channel'), name='notifications_preference_uniq'),
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['attendance', 'marks', 'homework', 'fees', 'bus', 'announcement', 'message', 'remark', 'approval', 'alert', 'learning']), ('channel__in', ['email', 'sms'])), name='notifications_preference_values_check'),
        ),
    ]
