# Generated by Django 6.1.1 on 2026-09-18 20:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(max_length=4000)),
                ('kind', models.CharField(choices=[('general', 'General'), ('event', 'Event'), ('holiday', 'Holiday'), ('exam', 'Exam'), ('transport', 'Transport'), ('safety', 'Safety')], default='general', max_length=10)),
                ('audience', models.CharField(choices=[('everyone', 'Everyone'), ('families', 'Parents and students'), ('staff', 'Staff'), ('classes', 'Selected classes')], default='everyone', max_length=10)),
                ('requires_ack', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField()),
                ('class_groups', models.ManyToManyField(blank=True, related_name='+', to='academics.classgroup')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementAck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acked_at', models.DateTimeField()),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acks', to='announcements.announcement')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('announcement', 'user'), name='uniq_announcement_ack')],
            },
        ),
    ]
