# Generated by Django 6.1.1 on 2026-09-26 15:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_event_ends_at_and_more'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='attachment',
            field=models.FileField(blank=True, upload_to='announcements/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='announcement',
            name='attachment_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announcement',
            name='channels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='announcement',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='audience',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('families', 'Parents and students'), ('staff', 'Staff'), ('classes', 'Selected classes'), ('parents', 'Parents only')], default='everyone', max_length=10),
        ),
        migrations.CreateModel(
            name='ChannelDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=160)),
                ('provider', models.CharField(max_length=30)),
                ('status', models.CharField(default='queued', max_length=12)),
                ('provider_ref', models.CharField(blank=True, max_length=80)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='announcements.announcement')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
