# Generated by Django 6.1.1 on 2026-09-26 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_announcement_attachment_announcement_attachment_name_and_more'),
        ('transport', '0002_alter_studenttransport_drop_stop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transport.route'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='audience',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('families', 'Parents and students'), ('staff', 'Staff'), ('classes', 'Selected classes'), ('parents', 'Parents only'), ('route', 'Families on a bus route')], default='everyone', max_length=10),
        ),
    ]
