# Generated by Django 6.1.1 on 2026-09-18 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='class_groups', to='academics.academicyear'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='students', to='academics.classgroup'),
        ),
    ]
