# Generated by Django 6.1.1 on 2026-09-26 10:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_classgroup_academic_year_and_more'),
        ('homework', '0002_alter_homework_subject'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='homework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remarks', to='homework.homework'),
        ),
        migrations.AddField(
            model_name='remark',
            name='requires_ack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remark',
            name='visibility',
            field=models.CharField(choices=[('family', 'Parent & student'), ('staff', 'Staff only')], default='family', max_length=8),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='note',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='RemarkAck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acks', to='academics.remark')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('remark', 'user'), name='uniq_remark_ack')],
            },
        ),
    ]
