# Generated by Django 6.1.1 on 2026-09-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_remark_homework_remark_requires_ack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='house',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
