# Generated by Django 5.2.18 on 2026-10-10 06:02

import django.db.models.deletion
import eduflow.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_term_room_integrity_and_rls'),
        ('people', '0004_enrollment_record_key'),
        ('tenancy', '0003_school_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('marks_deadline', models.DateField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.term')),
            ],
            options={
                'db_table': 'assessment_exam',
            },
        ),
        migrations.CreateModel(
            name='GradeBand',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=16)),
                ('min_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'assessment_grade_band',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('absent', models.BooleanField(default=False)),
                ('remark', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks', to='people.student')),
            ],
            options={
                'db_table': 'assessment_mark',
            },
        ),
        migrations.CreateModel(
            name='MarkCorrection',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('old_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('old_absent', models.BooleanField()),
                ('new_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('new_absent', models.BooleanField(default=False)),
                ('reason', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='assessment.mark')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'assessment_mark_correction',
            },
        ),
        migrations.CreateModel(
            name='MarkSheet',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pass_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('published', 'Published')], default='draft', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('return_note', models.CharField(blank=True, max_length=500)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='assessment.exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mark_sheets', to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.subject')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='people.staffprofile')),
            ],
            options={
                'db_table': 'assessment_mark_sheet',
            },
        ),
        migrations.AddField(
            model_name='mark',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='assessment.marksheet'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='assessment_exam_dates_check'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('marks_deadline__gte', models.F('ends_on'))), name='assessment_exam_deadline_check'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('academic_year', 'name'), name='assessment_exam_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='assessment_exam_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='gradeband',
            constraint=models.UniqueConstraint(fields=('school', 'min_percent'), name='assessment_band_min_uniq'),
        ),
        migrations.AddConstraint(
            model_name='gradeband',
            constraint=models.UniqueConstraint(fields=('school', 'label'), name='assessment_band_label_uniq'),
        ),
        migrations.AddConstraint(
            model_name='gradeband',
            constraint=models.CheckConstraint(condition=models.Q(('min_percent__gte', 0), ('min_percent__lte', 100)), name='assessment_band_range_check'),
        ),
        migrations.AddConstraint(
            model_name='markcorrection',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('mark',), name='assessment_one_pending_correction'),
        ),
        migrations.AddConstraint(
            model_name='markcorrection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('new_absent', True), ('new_marks__isnull', True)), models.Q(('new_absent', False), ('new_marks__gte', 0)), _connector='OR'), name='assessment_correction_value_check'),
        ),
        migrations.AddConstraint(
            model_name='markcorrection',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='assessment_mark_correction_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='marksheet',
            constraint=models.UniqueConstraint(fields=('exam', 'section', 'subject'), name='assessment_sheet_uniq'),
        ),
        migrations.AddConstraint(
            model_name='marksheet',
            constraint=models.CheckConstraint(condition=models.Q(('max_marks__gt', 0)), name='assessment_sheet_max_check'),
        ),
        migrations.AddConstraint(
            model_name='marksheet',
            constraint=models.CheckConstraint(condition=models.Q(('pass_marks__isnull', True), models.Q(('pass_marks__gte', 0), ('pass_marks__lte', models.F('max_marks'))), _connector='OR'), name='assessment_sheet_pass_check'),
        ),
        migrations.AddConstraint(
            model_name='marksheet',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft'), ('submitted_at__isnull', False), _connector='OR'), name='assessment_sheet_submitted_check'),
        ),
        migrations.AddConstraint(
            model_name='marksheet',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), ('published_at__isnull', False), _connector='OR'), name='assessment_sheet_published_check'),
        ),
        migrations.AddConstraint(
            model_name='marksheet',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='assessment_mark_sheet_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='mark',
            constraint=models.UniqueConstraint(fields=('sheet', 'student'), name='assessment_mark_uniq'),
        ),
        migrations.AddConstraint(
            model_name='mark',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('absent', True), ('marks__isnull', True)), models.Q(('absent', False), ('marks__gte', 0)), _connector='OR'), name='assessment_mark_value_check'),
        ),
        migrations.AddConstraint(
            model_name='mark',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='assessment_mark_id_school_uniq'),
        ),
    ]
