# Generated by Django 5.2.18 on 2026-10-10 06:19

import django.db.models.deletion
import django.db.models.expressions
import eduflow.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_term_room_integrity_and_rls'),
        ('documents', '0002_tenant_integrity_and_rls'),
        ('people', '0004_enrollment_record_key'),
        ('tenancy', '0003_school_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('positions', models.PositiveSmallIntegerField(default=1)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.department')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'hr_job_opening',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('stage', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('interview', 'Interview'), ('offer', 'Offer'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='applied', max_length=16)),
                ('notes', models.CharField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.storedfile')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='hr.jobopening')),
            ],
            options={
                'db_table': 'hr_candidate',
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('days_per_year', models.DecimalField(decimal_places=1, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'hr_leave_type',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.DecimalField(decimal_places=1, max_digits=5)),
                ('reason', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='people.staffprofile')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hr.leavetype')),
            ],
            options={
                'db_table': 'hr_leave_request',
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(help_text='The first day of the month paid.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processed', 'Processed'), ('paid', 'Paid')], default='draft', max_length=16)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'hr_payroll_run',
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('basic', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pf', models.DecimalField(decimal_places=2, max_digits=12)),
                ('esi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tds', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gross', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net', models.DecimalField(decimal_places=2, max_digits=12)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='hr.payrollrun')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='people.staffprofile')),
            ],
            options={
                'db_table': 'hr_payslip',
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('basic', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pf', models.DecimalField(decimal_places=2, default=0, help_text='Entered, not calculated.', max_digits=12)),
                ('esi', models.DecimalField(decimal_places=2, default=0, help_text='Entered, not calculated.', max_digits=12)),
                ('tds', models.DecimalField(decimal_places=2, default=0, help_text='Entered, not calculated.', max_digits=12)),
                ('bank_account_last4', models.CharField(blank=True, max_length=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='salary', to='people.staffprofile')),
            ],
            options={
                'db_table': 'hr_salary_structure',
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('leave', 'On leave')], max_length=16)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='days', to='people.staffprofile')),
            ],
            options={
                'db_table': 'hr_staff_attendance',
            },
        ),
        migrations.CreateModel(
            name='HrSettings',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('late_after', models.TimeField(help_text='A check-in after this school-local time is late.')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'hr_settings',
                'constraints': [models.UniqueConstraint(fields=('school',), name='hr_settings_school_uniq')],
            },
        ),
        migrations.AddConstraint(
            model_name='jobopening',
            constraint=models.CheckConstraint(condition=models.Q(('positions__gte', 1)), name='hr_opening_positions_check'),
        ),
        migrations.AddConstraint(
            model_name='jobopening',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='hr_job_opening_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='hr_candidate_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='hr_leave_type_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.CheckConstraint(condition=models.Q(('days_per_year__gte', 0)), name='hr_leave_type_days_check'),
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='hr_leave_type_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='hr_leave_dates_check'),
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.CheckConstraint(condition=models.Q(('days__gt', 0)), name='hr_leave_days_check'),
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='hr_leave_request_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('school', 'month'), name='hr_payroll_month_uniq'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.CheckConstraint(condition=models.Q(('month__day', 1)), name='hr_payroll_month_check'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='hr_payroll_run_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('run', 'staff'), name='hr_payslip_uniq'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.CheckConstraint(condition=models.Q(('gross', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('basic'), '+', models.F('hra')), '+', models.F('allowances'))), ('deductions', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('pf'), '+', models.F('esi')), '+', models.F('tds'))), ('net', django.db.models.expressions.CombinedExpression(models.F('gross'), '-', models.F('deductions')))), name='hr_payslip_sums_check'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='hr_payslip_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='salarystructure',
            constraint=models.CheckConstraint(condition=models.Q(('basic__gte', 0), ('hra__gte', 0), ('allowances__gte', 0), ('pf__gte', 0), ('esi__gte', 0), ('tds__gte', 0)), name='hr_salary_non_negative_check'),
        ),
        migrations.AddConstraint(
            model_name='salarystructure',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='hr_salary_structure_id_school_uniq'),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['school', 'date'], name='hr_staff_day_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffattendance',
            constraint=models.UniqueConstraint(fields=('staff', 'date'), name='hr_staff_day_uniq'),
        ),
        migrations.AddConstraint(
            model_name='staffattendance',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['present', 'late', 'absent', 'leave'])), name='hr_staff_day_status_check'),
        ),
        migrations.AddConstraint(
            model_name='staffattendance',
            constraint=models.CheckConstraint(condition=models.Q(('check_out__isnull', True), models.Q(('check_in__isnull', False), ('check_out__gte', models.F('check_in'))), _connector='OR'), name='hr_staff_day_times_check'),
        ),
        migrations.AddConstraint(
            model_name='staffattendance',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='hr_staff_attendance_id_school_uniq'),
        ),
    ]
