# Generated by Django 6.1.1 on 2026-09-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='teaser',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
