# Generated by Django 6.1.1 on 2026-09-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_assignment_teaser'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabusprogress',
            name='planned_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
