# Generated by Django 5.2.18 on 2026-10-09 06:34

import django.db.models.deletion
import eduflow.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_tenant_integrity_and_rls'),
        ('authz', '0002_tenant_integrity_and_rls'),
        ('people', '0002_tenant_integrity_and_rls'),
        ('tenancy', '0003_school_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('staff', 'Staff member or teacher'), ('student', 'Student'), ('guardian', 'Parent or guardian')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('phone', 'Mobile number')], max_length=8)),
                ('recipient', models.CharField(help_text='Normalised email address or E.164 mobile number.', max_length=254)),
                ('full_name', models.CharField(help_text='Used only if acceptance creates a new account.', max_length=200)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('employee_id', models.CharField(blank=True, max_length=32)),
                ('staff_type', models.CharField(blank=True, choices=[('teaching', 'Teaching'), ('non_teaching', 'Non-teaching')], max_length=16)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('expires_at', models.DateTimeField()),
                ('last_sent_at', models.DateTimeField()),
                ('send_count', models.PositiveSmallIntegerField(default=1)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.membership')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.campus')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.department')),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='people.guardian')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.membership')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='people.student')),
            ],
            options={
                'db_table': 'invitations_invitation',
            },
        ),
        migrations.CreateModel(
            name='InvitationRole',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_links', to='invitations.invitation')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='authz.role')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'invitations_invitation_role',
            },
        ),
        migrations.AddField(
            model_name='invitation',
            name='roles',
            field=models.ManyToManyField(related_name='+', through='invitations.InvitationRole', to='authz.role'),
        ),
        migrations.AddConstraint(
            model_name='invitationrole',
            constraint=models.UniqueConstraint(fields=('invitation', 'role'), name='invitations_invitation_role_uniq'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['school', 'status'], name='invitations_school_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(condition=models.Q(('status', 'pending')), fields=['expires_at'], name='invitations_pending_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('employee_id', ''), ('guardian__isnull', True), ('kind', 'student'), ('student__isnull', False)), models.Q(('employee_id', ''), ('guardian__isnull', False), ('kind', 'guardian'), ('student__isnull', True)), models.Q(('guardian__isnull', True), ('kind', 'staff'), ('student__isnull', True), models.Q(('employee_id', ''), _negated=True), models.Q(('staff_type', ''), _negated=True)), _connector='OR'), name='invitations_invitation_target_matches_kind_check'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accepted_at__isnull', False), ('accepted_membership__isnull', False), ('status', 'accepted')), models.Q(models.Q(('status', 'accepted'), _negated=True), ('accepted_at__isnull', True)), _connector='OR'), name='invitations_invitation_accepted_check'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', False), ('status', 'revoked')), models.Q(models.Q(('status', 'revoked'), _negated=True), ('revoked_at__isnull', True)), _connector='OR'), name='invitations_invitation_revoked_check'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('school', 'kind', 'channel', 'recipient'), name='invitations_one_pending_per_recipient_uniq'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('student',), name='invitations_one_pending_per_student_uniq'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('guardian',), name='invitations_one_pending_per_guardian_uniq'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='invitations_invitation_id_school_uniq'),
        ),
    ]
