# Generated by Django 6.1.1 on 2026-09-26 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_student_house'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='locked_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(blank=True, choices=[('', '—'), ('submitted', 'Sent to exam cell'), ('accepted', 'Accepted'), ('in_review', 'In review'), ('verified', 'Verified')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.subject'),
        ),
        migrations.AlterField(
            model_name='document',
            name='audience',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('families', 'All families'), ('classes', 'Families of some classes'), ('student', "One student's family"), ('staff', 'Staff'), ('private', 'Owner only')], default='families', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='kind',
            field=models.CharField(choices=[('circular', 'Circular'), ('report_card', 'Report card'), ('certificate', 'Certificate'), ('policy', 'Policy'), ('lesson_plan', 'Lesson plan'), ('question_paper', 'Question paper'), ('payslip', 'Payslip'), ('other', 'Other')], max_length=16),
        ),
    ]
