# Generated by Django 6.1.1 on 2026-09-26 16:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_subjectvacancy_timetablerevision_timetabledraft'),
        ('documents', '0002_document_locked_until_document_status_and_more'),
        ('tenancy', '0001_initial'),
        ('transport', '0002_alter_studenttransport_drop_stop_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pages',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='documentdownload',
            name='action',
            field=models.CharField(choices=[('download', 'Downloaded'), ('view', 'Viewed'), ('permissions', 'Changed permissions'), ('upload', 'Uploaded')], default='download', max_length=12),
        ),
        migrations.AddField(
            model_name='documentdownload',
            name='device',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='DocumentGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(choices=[('staff', 'All staff'), ('class_teacher', 'Class teacher'), ('teachers', 'Teachers'), ('parents', 'Parents'), ('students', 'Students'), ('accountant', 'Accountant')], max_length=16)),
                ('can_view', models.BooleanField(default=False)),
                ('can_download', models.BooleanField(default=False)),
                ('can_upload', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('class_groups', models.ManyToManyField(blank=True, related_name='+', to='academics.classgroup')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='documents.document')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transport.route')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('locked', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.folder')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.folder'),
        ),
    ]
