# Generated by Django 6.1.1 on 2026-09-18 20:04

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=80)),
                ('path', models.JSONField(default=list, help_text='[[lat, lng], ...] from the depot to the school gate')),
                ('length_m', models.FloatField(default=0)),
                ('avg_speed_kmh', models.FloatField(default=22)),
                ('pickup_start', models.TimeField(default=datetime.time(7, 10))),
                ('drop_start', models.TimeField(default=datetime.time(15, 40))),
                ('is_active', models.BooleanField(default=True)),
                ('attendant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('sequence', models.PositiveSmallIntegerField(help_text='Order on the morning pickup')),
                ('radius_m', models.PositiveSmallIntegerField(default=75)),
                ('pickup_offset_min', models.PositiveSmallIntegerField(default=0)),
                ('drop_offset_min', models.PositiveSmallIntegerField(default=0)),
                ('is_school', models.BooleanField(default=False)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='transport.route')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
            ],
            options={
                'ordering': ['route', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='StudentTransport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('drop_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transport.stop')),
                ('pickup_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transport.stop')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riders', to='transport.route')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='academics.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransportAbsence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_date', models.DateField()),
                ('direction', models.CharField(choices=[('pickup', 'Morning'), ('drop', 'Afternoon'), ('both', 'Both')], default='both', max_length=8)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academics.student')),
            ],
        ),
        migrations.CreateModel(
            name='TransportPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_minutes', models.PositiveSmallIntegerField(default=10)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academics.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('pickup', 'Morning pickup'), ('drop', 'Afternoon drop')], max_length=8)),
                ('service_date', models.DateField()),
                ('scheduled_start', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'On the way'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_position_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('empty_check_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('auto_closed', models.BooleanField(default=False)),
                ('attendant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='transport.route')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
            ],
            options={
                'ordering': ['service_date', 'scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='BoardingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('boarded', 'Boarded'), ('dropped', 'Dropped off'), ('no_show', 'Not at the stop')], max_length=10)),
                ('at', models.DateTimeField()),
                ('client_id', models.CharField(blank=True, max_length=64, null=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academics.student')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_events', to='transport.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('sos', 'SOS'), ('speeding', 'Speeding'), ('off_route', 'Off route'), ('stop_skipped', 'Stop skipped'), ('signal_lost', 'GPS signal lost'), ('empty_check_missing', 'Bus-empty check not confirmed')], max_length=24)),
                ('at', models.DateTimeField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='transport.trip')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='TripPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('speed_mps', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('source', models.CharField(choices=[('driver_app', 'Driver app'), ('device', 'GPS device'), ('simulator', 'Simulator')], max_length=12)),
                ('client_id', models.CharField(blank=True, max_length=64, null=True)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='transport.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripStopEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('arrived', 'Arrived'), ('departed', 'Departed'), ('skipped', 'Skipped')], max_length=10)),
                ('at', models.DateTimeField()),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transport.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_events', to='transport.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripViewLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_viewed_at', models.DateTimeField()),
                ('last_viewed_at', models.DateTimeField()),
                ('views', models.PositiveIntegerField(default=1)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transport.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_no', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=40)),
                ('capacity', models.PositiveSmallIntegerField(default=40)),
                ('gps_device_id', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('last_lat', models.FloatField(blank=True, null=True)),
                ('last_lng', models.FloatField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('has_gps_tracker', models.BooleanField(default=False)),
                ('has_panic_button', models.BooleanField(default=False)),
                ('has_cctv', models.BooleanField(default=False)),
                ('has_speed_governor', models.BooleanField(default=False)),
                ('fitness_valid_until', models.DateField(blank=True, null=True)),
                ('permit_valid_until', models.DateField(blank=True, null=True)),
                ('insurance_valid_until', models.DateField(blank=True, null=True)),
                ('puc_valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='transport.vehicle'),
        ),
        migrations.AddField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='transport.vehicle'),
        ),
        migrations.AddConstraint(
            model_name='stop',
            constraint=models.UniqueConstraint(fields=('route', 'sequence'), name='uniq_stop_sequence'),
        ),
        migrations.AddConstraint(
            model_name='transportabsence',
            constraint=models.UniqueConstraint(fields=('student', 'service_date', 'direction'), name='uniq_transport_absence'),
        ),
        migrations.AddConstraint(
            model_name='transportpreference',
            constraint=models.UniqueConstraint(fields=('user', 'student'), name='uniq_transport_pref'),
        ),
        migrations.AddConstraint(
            model_name='boardingevent',
            constraint=models.UniqueConstraint(fields=('trip', 'student', 'kind'), name='uniq_boarding_event'),
        ),
        migrations.AddIndex(
            model_name='tripposition',
            index=models.Index(fields=['trip', 'recorded_at'], name='trip_position_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='tripposition',
            constraint=models.UniqueConstraint(condition=models.Q(('client_id__isnull', False)), fields=('trip', 'client_id'), name='uniq_position_client_id'),
        ),
        migrations.AddConstraint(
            model_name='tripstopevent',
            constraint=models.UniqueConstraint(fields=('trip', 'stop', 'kind'), name='uniq_trip_stop_event'),
        ),
        migrations.AddConstraint(
            model_name='tripviewlog',
            constraint=models.UniqueConstraint(fields=('trip', 'user'), name='uniq_trip_view_log'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['school', 'service_date', 'status'], name='trip_day_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(fields=('route', 'direction', 'service_date'), name='uniq_trip_per_day'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='uniq_route_code'),
        ),
    ]
