# Generated by Django 6.1.1 on 2026-09-18 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttransport',
            name='drop_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='transport.stop'),
        ),
        migrations.AlterField(
            model_name='studenttransport',
            name='pickup_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='transport.stop'),
        ),
    ]
