# Generated by Django 6.1.1 on 2026-09-26 16:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_subjectvacancy_timetablerevision_timetabledraft'),
        ('tenancy', '0001_initial'),
        ('transport', '0002_alter_studenttransport_drop_stop_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripincident',
            name='kind',
            field=models.CharField(choices=[('sos', 'SOS'), ('speeding', 'Speeding'), ('off_route', 'Off route'), ('stop_skipped', 'Stop skipped'), ('signal_lost', 'GPS signal lost'), ('empty_check_missing', 'Bus-empty check not confirmed'), ('delay', 'Running late')], max_length=24),
        ),
        migrations.CreateModel(
            name='TransportException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('held', 'Held at pickup'), ('stop_change', 'Stop change'), ('not_scanned', 'Not scanned'), ('off_manifest', 'Off manifest')], max_length=14)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('occurred_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('from_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transport.stop')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='transport.route')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
                ('students', models.ManyToManyField(blank=True, related_name='+', to='academics.student')),
                ('to_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transport.stop')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions', to='transport.trip')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['school', 'occurred_at'], name='transport_exc_day_idx')],
            },
        ),
    ]
