# Generated by Django 6.1.1 on 2026-09-26 16:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalevent',
            name='action',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('checked', 'Checked'), ('approved', 'Approved'), ('declined', 'Declined'), ('sent_back', 'Sent back'), ('undone', 'Undone'), ('withdrawn', 'Withdrawn')], max_length=10),
        ),
        migrations.CreateModel(
            name='ApprovalAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='approvals/%Y/%m/')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('document', 'Document'), ('scan', 'Scanned pages')], default='document', max_length=10)),
                ('pages', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('size', models.PositiveIntegerField(default=0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='approvals.approvalrequest')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
