# Generated by Django 5.2.18 on 2026-10-10 07:01

import django.db.models.deletion
import eduflow.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0004_enrollment_record_key'),
        ('tenancy', '0003_school_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('visitor_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=32)),
                ('purpose', models.CharField(max_length=300)),
                ('visitors_count', models.PositiveSmallIntegerField(default=1)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('id_proof', models.CharField(blank=True, help_text='Kind and last digits only.', max_length=100)),
                ('expected_on', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('declined', 'Declined'), ('inside', 'Checked in'), ('left', 'Checked out'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=300)),
                ('pass_hash', models.CharField(blank=True, max_length=64)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='people.student')),
            ],
            options={
                'db_table': 'visitors_visit',
                'indexes': [models.Index(fields=['school', 'expected_on'], name='visitors_day_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('pass_hash', ''), _negated=True), fields=('pass_hash',), name='visitors_pass_uniq'), models.CheckConstraint(condition=models.Q(('visitors_count__gte', 1)), name='visitors_min_count_check'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'inside'), _negated=True), ('checked_in_at__isnull', False), _connector='OR'), name='visitors_inside_check'), models.UniqueConstraint(fields=('id', 'school'), name='visitors_visit_id_school_uniq')],
            },
        ),
    ]
