# Generated by Django 5.2.18 on 2026-10-09 11:04

import django.db.models.deletion
import eduflow.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_term_room_integrity_and_rls'),
        ('people', '0003_assignment_slot_key'),
        ('tenancy', '0003_school_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('submitted_at', models.DateTimeField()),
                ('locked_at', models.DateTimeField(help_text='After this moment the register changes only by correction.')),
                ('client_id', models.CharField(blank=True, help_text='Idempotency key of the last submission.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='academics.section')),
                ('taken_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.membership')),
            ],
            options={
                'db_table': 'attendance_session',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half day'), ('excused', 'Excused')], max_length=16)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='people.enrollment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('section', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='people.student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession')),
            ],
            options={
                'db_table': 'attendance_record',
            },
        ),
        migrations.CreateModel(
            name='AttendanceCorrection',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half day'), ('excused', 'Excused')], max_length=16)),
                ('new_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half day'), ('excused', 'Excused')], max_length=16)),
                ('reason', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.membership')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='attendance.attendancerecord')),
            ],
            options={
                'db_table': 'attendance_correction',
                'indexes': [models.Index(fields=['school', 'status'], name='attendance_corr_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('old_status__in', ['present', 'absent', 'late', 'half_day', 'excused'])), name='attendance_correction_old_status_check'), models.CheckConstraint(condition=models.Q(('new_status__in', ['present', 'absent', 'late', 'half_day', 'excused'])), name='attendance_correction_new_status_check'), models.CheckConstraint(condition=models.Q(('old_status', models.F('new_status')), _negated=True), name='attendance_correction_changes_status_check'), models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='attendance_correction_reason_check'), models.CheckConstraint(condition=models.Q(models.Q(('decided_at__isnull', True), ('decided_by__isnull', True), ('status', 'pending')), models.Q(('status__in', ['approved', 'declined']), ('decided_at__isnull', False), ('decided_by__isnull', False)), _connector='OR'), name='attendance_correction_decision_check'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('record',), name='attendance_correction_one_pending_uniq'), models.UniqueConstraint(fields=('id', 'school'), name='attendance_correction_id_school_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['school', 'date'], name='attendance_sess_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(fields=('section', 'date'), name='attendance_session_section_date_uniq'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='attendance_session_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(fields=('id', 'section', 'date', 'school'), name='attendance_session_record_key_uniq'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['school', 'student', 'date'], name='attendance_rec_student_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['school', 'section', 'date'], name='attendance_rec_section_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='attendance_record_session_student_uniq'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['present', 'absent', 'late', 'half_day', 'excused'])), name='attendance_record_status_check'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='attendance_record_id_school_uniq'),
        ),
    ]
