# Generated by Django 5.2.18 on 2026-10-09 09:06

import django.contrib.postgres.constraints
import django.db.models.deletion
import django.db.models.functions.text
import eduflow.academics.models
import eduflow.core.ids
import eduflow.timetable.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_room_term'),
        ('people', '0003_assignment_slot_key'),
        ('tenancy', '0003_school_profile'),
    ]

    operations = [
        # A range of times of day, for the clash exclusion constraints (eduflow.timetable.models.TimeRange).
        migrations.RunSQL(
            "CREATE TYPE eduflow_timerange AS RANGE (subtype = time);",
            "DROP TYPE IF EXISTS eduflow_timerange;",
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('is_live', models.BooleanField(default=False, editable=False, help_text='Equals status == published.')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetables', to='academics.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetables', to='academics.term')),
            ],
            options={
                'db_table': 'timetable_timetable',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(help_text='For example "Period 1" or "Lunch".', max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_break', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='timetable.timetable')),
            ],
            options={
                'db_table': 'timetable_period',
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.PositiveSmallIntegerField(help_text='ISO weekday: 1 = Monday ... 7 = Sunday.')),
                ('kind', models.CharField(choices=[('lesson', 'Lesson'), ('activity', 'Activity')], default='lesson', max_length=16)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('effective_from', models.DateField(editable=False)),
                ('effective_to', models.DateField(editable=False)),
                ('is_live', models.BooleanField(editable=False)),
                ('start_time', models.TimeField(editable=False)),
                ('end_time', models.TimeField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.academicyear')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to='people.teacherassignment')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='slots', to='timetable.period')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='academics.room')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_slots', to='academics.section')),
                ('staff', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='people.staffprofile')),
                ('subject', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='academics.subject')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='timetable.timetable')),
            ],
            options={
                'db_table': 'timetable_slot',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('held', 'Held'), ('cancelled', 'Cancelled')], default='held', max_length=16)),
                ('topic', models.CharField(blank=True, max_length=300)),
                ('cancellation_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='academics.section')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='people.staffprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='academics.subject')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='timetable.timetableslot')),
            ],
            options={
                'db_table': 'timetable_lesson',
            },
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['school', 'academic_year', 'status'], name='timetable_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.CheckConstraint(condition=models.Q(('effective_from__lte', models.F('effective_to'))), name='timetable_timetable_dates_check'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_live', True), ('status', 'published')), models.Q(('is_live', False), models.Q(('status', 'published'), _negated=True)), _connector='OR'), name='timetable_timetable_live_is_published_check'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft'), ('published_at__isnull', False), _connector='OR'), name='timetable_timetable_published_at_check'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'archived'), _negated=True), ('archived_at__isnull', False), _connector='OR'), name='timetable_timetable_archived_at_check'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(models.F('academic_year'), django.db.models.functions.text.Lower('name'), name='timetable_timetable_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='timetable_timetable_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('id', 'academic_year', 'effective_from', 'effective_to', 'is_live', 'school'), name='timetable_timetable_slot_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='timetable_period_times_check'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1)), name='timetable_period_number_positive_check'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('timetable', 'number'), name='timetable_period_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('timetable', '='), (eduflow.timetable.models.TimeRange('start_time', 'end_time'), '&&')], name='timetable_period_no_overlap'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='timetable_period_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('id', 'timetable', 'start_time', 'end_time', 'school'), name='timetable_period_slot_key_uniq'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['school', 'timetable', 'weekday'], name='timetable_slot_day_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['school', 'section', 'weekday'], name='timetable_slot_section_idx'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 1), ('weekday__lte', 7)), name='timetable_slot_weekday_range_check'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assignment__isnull', False), ('kind', 'lesson'), ('staff__isnull', False), ('subject__isnull', False)), models.Q(('assignment__isnull', True), ('kind', 'activity'), ('staff__isnull', True), ('subject__isnull', True), models.Q(('title', ''), _negated=True)), _connector='OR'), name='timetable_slot_kind_check'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.UniqueConstraint(fields=('period', 'weekday', 'section'), name='timetable_slot_section_uniq'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.UniqueConstraint(condition=models.Q(('staff__isnull', False)), fields=('period', 'weekday', 'staff'), name='timetable_slot_staff_uniq'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.UniqueConstraint(condition=models.Q(('room__isnull', False)), fields=('period', 'weekday', 'room'), name='timetable_slot_room_uniq'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('is_live', True)), expressions=[('section', '='), ('weekday', '='), (eduflow.timetable.models.TimeRange('start_time', 'end_time'), '&&'), (eduflow.academics.models.DateRange('effective_from', 'effective_to', models.Value('[]')), '&&')], name='timetable_slot_live_section_excl'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('is_live', True), ('staff__isnull', False)), expressions=[('staff', '='), ('weekday', '='), (eduflow.timetable.models.TimeRange('start_time', 'end_time'), '&&'), (eduflow.academics.models.DateRange('effective_from', 'effective_to', models.Value('[]')), '&&')], name='timetable_slot_live_staff_excl'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('is_live', True), ('room__isnull', False)), expressions=[('room', '='), ('weekday', '='), (eduflow.timetable.models.TimeRange('start_time', 'end_time'), '&&'), (eduflow.academics.models.DateRange('effective_from', 'effective_to', models.Value('[]')), '&&')], name='timetable_slot_live_room_excl'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='timetable_slot_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.UniqueConstraint(fields=('id', 'section', 'school'), name='timetable_slot_lesson_key_uniq'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['school', 'section', 'date'], name='timetable_lesson_section_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['school', 'staff', 'date'], name='timetable_lesson_staff_idx'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('slot', 'date'), name='timetable_lesson_slot_date_uniq'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'cancelled'), ('cancellation_reason', ''), _connector='OR'), name='timetable_lesson_reason_only_when_cancelled_check'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='timetable_lesson_id_school_uniq'),
        ),
    ]
