# Generated by Django 6.1.1 on 2026-09-18 20:04

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('tuition', 'Tuition'), ('transport', 'Transport'), ('hostel', 'Hostel'), ('exam', 'Exam'), ('other', 'Other')], default='tuition', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('due_date', models.DateField()),
                ('gst_exempt', models.BooleanField(default=True)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='academics.student')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gateway', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('created', 'Awaiting payment'), ('succeeded', 'Paid'), ('failed', 'Failed')], default='created', max_length=10)),
                ('gateway_order_id', models.CharField(blank=True, max_length=80)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=80)),
                ('receipt_no', models.CharField(blank=True, max_length=40, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='fees.feeinvoice')),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('receipt_no__isnull', False)), fields=('school', 'receipt_no'), name='uniq_receipt_no'), models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('school', 'idempotency_key'), name='uniq_payment_idempotency')],
            },
        ),
        migrations.CreateModel(
            name='ReceiptCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_year', models.CharField(max_length=9)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('school', 'financial_year'), name='uniq_receipt_counter')],
            },
        ),
    ]
