# Generated by Django 6.1.1 on 2026-09-26 15:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_payment_method_feeinvoiceitem'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_head', models.CharField(blank=True, max_length=60)),
                ('reason', models.CharField(max_length=400)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('declined', 'Declined')], default='requested', max_length=10)),
                ('asked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='refunds', to='fees.payment')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
