# Generated by Django 6.1.1 on 2026-09-26 16:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_refund'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeinvoice',
            name='category',
            field=models.CharField(choices=[('tuition', 'Tuition'), ('transport', 'Transport'), ('hostel', 'Hostel'), ('exam', 'Exam'), ('activity', 'Activity'), ('other', 'Other')], default='tuition', max_length=12),
        ),
        migrations.CreateModel(
            name='InstalmentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instalments', models.JSONField(default=list, help_text='[{"due_on": "2026-10-15", "amount": "14000"}, ...]')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('agreed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='fees.feeinvoice')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeeReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_ids', models.JSONField(default=list)),
                ('channels', models.JSONField(default=list)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read, no reply'), ('not_opened', 'Not opened'), ('failed', 'Failed'), ('answered', 'Answered'), ('no_answer', 'No answer')], default='sent', max_length=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('deliveries', models.JSONField(blank=True, default=dict)),
                ('batch', models.UUIDField(blank=True, db_index=True, null=True)),
                ('sent_at', models.DateTimeField()),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['guardian', '-sent_at'], name='fee_reminder_guardian_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.CharField(max_length=9)),
                ('band', models.CharField(help_text="Label shown in the table, e.g. 'Pre-primary' or '6–8'", max_length=40)),
                ('grades', models.JSONField(default=list, help_text='ClassGroup.grade values the band covers')),
                ('head', models.CharField(choices=[('tuition', 'Tuition'), ('transport', 'Transport'), ('activity', 'Activity')], max_length=12)),
                ('annual_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_dates', models.JSONField(default=list, help_text='ISO dates the instalments fall due')),
                ('optional', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
            ],
            options={
                'ordering': ['order', 'head'],
                'constraints': [models.UniqueConstraint(fields=('school', 'academic_year', 'band', 'head'), name='uniq_fee_structure')],
            },
        ),
    ]
