# Generated by Django 5.2.18 on 2026-10-10 06:48

import django.db.models.deletion
import eduflow.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0004_enrollment_record_key'),
        ('tenancy', '0003_school_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('warden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
            ],
            options={
                'db_table': 'hostel_hostel',
            },
        ),
        migrations.CreateModel(
            name='Outpass',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('leave_at', models.DateTimeField()),
                ('return_by', models.DateTimeField()),
                ('reason', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('out', 'Out'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=500)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outpasses', to='people.student')),
            ],
            options={
                'db_table': 'hostel_outpass',
            },
        ),
        migrations.CreateModel(
            name='RollCall',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('on_outpass', 'On outpass')], max_length=16)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roll', to='hostel.hostel')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hostel_roll', to='people.student')),
            ],
            options={
                'db_table': 'hostel_roll_call',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20)),
                ('beds', models.PositiveSmallIntegerField()),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='hostel.hostel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'hostel_room',
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hostel_allocations', to='people.student')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='hostel.room')),
            ],
            options={
                'db_table': 'hostel_allocation',
            },
        ),
        migrations.AddConstraint(
            model_name='hostel',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='hostel_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='hostel',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='hostel_hostel_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='outpass',
            constraint=models.CheckConstraint(condition=models.Q(('return_by__gt', models.F('leave_at'))), name='hostel_outpass_window_check'),
        ),
        migrations.AddConstraint(
            model_name='outpass',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='hostel_outpass_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='rollcall',
            constraint=models.UniqueConstraint(fields=('student', 'date'), name='hostel_roll_uniq'),
        ),
        migrations.AddConstraint(
            model_name='rollcall',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='hostel_roll_call_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('hostel', 'number'), name='hostel_room_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('beds__gte', 1)), name='hostel_room_min_beds_check'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='hostel_room_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('student',), name='hostel_one_active_allocation'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='hostel_allocation_dates_check'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='hostel_allocation_id_school_uniq'),
        ),
    ]
