# Generated by Django 5.2.18 on 2026-10-09 12:30

import django.db.models.deletion
import django.db.models.functions.text
import eduflow.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0003_school_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandAsset',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('logo', 'Logo'), ('favicon', 'Favicon')], max_length=16)),
                ('content_type', models.CharField(max_length=64)),
                ('size', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('storage_key', models.CharField(help_text='Internal; never returned by the API.', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
            ],
            options={
                'db_table': 'branding_asset',
            },
        ),
        migrations.CreateModel(
            name='SchoolBranding',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('primary_color', models.CharField(blank=True, help_text='#RRGGBB; empty = platform default.', max_length=7)),
                ('secondary_color', models.CharField(blank=True, help_text='#RRGGBB; empty = platform default.', max_length=7)),
                ('version', models.PositiveIntegerField(default=1, help_text='Bumped on every change; part of the ETag.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='branding.brandasset')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='branding.brandasset')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='branding', to='tenancy.school')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
            ],
            options={
                'db_table': 'branding_school_branding',
            },
        ),
        migrations.CreateModel(
            name='SchoolDomain',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(help_text='Lower-case, ASCII (IDNA) form.', max_length=253)),
                ('status', models.CharField(choices=[('pending', 'Pending verification'), ('verified', 'Verified'), ('disabled', 'Disabled')], default='pending', max_length=16)),
                ('is_primary', models.BooleanField(default=False)),
                ('verification_token', models.CharField(help_text='Published by the owner in DNS; not a secret.', max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('check_failures', models.PositiveSmallIntegerField(default=0)),
                ('disabled_reason', models.CharField(blank=True, max_length=32)),
                ('suspended_by_platform', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'branding_domain',
            },
        ),
        migrations.AddConstraint(
            model_name='brandasset',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['logo', 'favicon'])), name='branding_asset_kind_check'),
        ),
        migrations.AddConstraint(
            model_name='brandasset',
            constraint=models.CheckConstraint(condition=models.Q(('content_type__in', ['image/png', 'image/jpeg', 'image/webp', 'image/x-icon'])), name='branding_asset_content_type_check'),
        ),
        migrations.AddConstraint(
            model_name='brandasset',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='branding_asset_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='schoolbranding',
            constraint=models.CheckConstraint(condition=models.Q(('primary_color', ''), ('primary_color__regex', '^#[0-9A-Fa-f]{6}$'), _connector='OR'), name='branding_primary_color_check'),
        ),
        migrations.AddConstraint(
            model_name='schoolbranding',
            constraint=models.CheckConstraint(condition=models.Q(('secondary_color', ''), ('secondary_color__regex', '^#[0-9A-Fa-f]{6}$'), _connector='OR'), name='branding_secondary_color_check'),
        ),
        migrations.AddIndex(
            model_name='schooldomain',
            index=models.Index(fields=['status'], name='branding_domain_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='schooldomain',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('hostname'), name='branding_domain_hostname_uniq'),
        ),
        migrations.AddConstraint(
            model_name='schooldomain',
            constraint=models.CheckConstraint(condition=models.Q(('hostname', django.db.models.functions.text.Lower('hostname'))), name='branding_domain_lowercase_check'),
        ),
        migrations.AddConstraint(
            model_name='schooldomain',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'verified', 'disabled'])), name='branding_domain_status_check'),
        ),
        migrations.AddConstraint(
            model_name='schooldomain',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'verified'), _negated=True), ('verified_at__isnull', False), _connector='OR'), name='branding_domain_verified_at_check'),
        ),
        migrations.AddConstraint(
            model_name='schooldomain',
            constraint=models.CheckConstraint(condition=models.Q(('is_primary', False), ('status', 'verified'), _connector='OR'), name='branding_domain_primary_is_verified_check'),
        ),
        migrations.AddConstraint(
            model_name='schooldomain',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('school',), name='branding_domain_one_primary_uniq'),
        ),
        migrations.AddConstraint(
            model_name='schooldomain',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='branding_domain_id_school_uniq'),
        ),
    ]
