# Generated by Django 5.2.18 on 2026-10-10 01:39

import django.db.models.deletion
import eduflow.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_term_room_integrity_and_rls'),
        ('documents', '0002_tenant_integrity_and_rls'),
        ('people', '0004_enrollment_record_key'),
        ('tenancy', '0003_school_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('child_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('parent_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('source', models.CharField(choices=[('website', 'Website'), ('walk_in', 'Walk-in'), ('referral', 'Referral'), ('social', 'Social'), ('newspaper', 'Newspaper')], max_length=16)),
                ('stage', models.CharField(choices=[('enquiry', 'Enquiry'), ('visit', 'Visit'), ('assessment', 'Assessment'), ('offer', 'Offer'), ('enrolled', 'Enrolled'), ('dropped', 'Dropped')], default='enquiry', max_length=16)),
                ('notes', models.CharField(blank=True, max_length=2000)),
                ('fee_quoted', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('offer_decision', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], max_length=16)),
                ('offer_requested_at', models.DateTimeField(blank=True, null=True)),
                ('offer_decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('enrollment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='people.enrollment')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.grade')),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='people.guardian')),
                ('offer_decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('offer_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='people.student')),
            ],
            options={
                'db_table': 'admissions_application',
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.application')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.storedfile')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'admissions_document',
            },
        ),
        migrations.CreateModel(
            name='StageChange',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('from_stage', models.CharField(blank=True, choices=[('enquiry', 'Enquiry'), ('visit', 'Visit'), ('assessment', 'Assessment'), ('offer', 'Offer'), ('enrolled', 'Enrolled'), ('dropped', 'Dropped')], max_length=16)),
                ('to_stage', models.CharField(choices=[('enquiry', 'Enquiry'), ('visit', 'Visit'), ('assessment', 'Assessment'), ('offer', 'Offer'), ('enrolled', 'Enrolled'), ('dropped', 'Dropped')], max_length=16)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='admissions.application')),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'admissions_stage_change',
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['school', 'stage'], name='admissions_stage_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('stage__in', ['enquiry', 'visit', 'assessment', 'offer', 'enrolled', 'dropped'])), name='admissions_stage_check'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('fee_quoted__isnull', True), ('fee_quoted__gte', 0), _connector='OR'), name='admissions_fee_check'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('stage', 'enrolled'), _negated=True), models.Q(('student__isnull', False), ('enrollment__isnull', False)), _connector='OR'), name='admissions_enrolled_has_student_check'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('stage', 'enrolled'), _negated=True), ('offer_decision', 'approved'), _connector='OR'), name='admissions_enrolled_needs_approval_check'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='admissions_application_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='applicationdocument',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='admissions_document_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='stagechange',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='admissions_stage_change_id_school_uniq'),
        ),
    ]
