# Generated by Django 5.2.18 on 2026-10-08 14:23

import django.db.models.deletion
import django.db.models.functions.text
import eduflow.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_platform_admin', models.BooleanField(default=False)),
                ('must_change_password', models.BooleanField(default=False)),
                ('language', models.CharField(default='en', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'identity_user',
                'constraints': [models.CheckConstraint(condition=models.Q(('email__isnull', False), ('phone__isnull', False), _connector='OR'), name='identity_user_email_or_phone_check'), models.CheckConstraint(condition=models.Q(('email__isnull', True), ('email', django.db.models.functions.text.Lower('email')), _connector='OR'), name='identity_user_email_lowercase_check'), models.CheckConstraint(condition=models.Q(('phone__isnull', True), ('phone__regex', '^\\+[1-9][0-9]{7,14}$'), _connector='OR'), name='identity_user_phone_e164_check')],
            },
        ),
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('auth_method', models.CharField(choices=[('password', 'Password'), ('otp', 'One-time code')], max_length=16)),
                ('remember', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(help_text='Absolute end of the session, whatever the rotation.')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, choices=[('logout', 'Signed out'), ('logout_all', 'Signed out everywhere'), ('reuse_detected', 'Refresh token reuse detected'), ('password_changed', 'Password changed'), ('user_deactivated', 'Account deactivated'), ('session_revoked', 'Revoked by the user')], max_length=32)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'identity_auth_session',
            },
        ),
        migrations.CreateModel(
            name='OtpChallenge',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('login', 'Sign in')], default='login', max_length=16)),
                ('phone_hash', models.CharField(max_length=64)),
                ('code_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'identity_otp_challenge',
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('replaced_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='identity.refreshtoken')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='identity.authsession')),
            ],
            options={
                'db_table': 'identity_refresh_token',
            },
        ),
        migrations.AddIndex(
            model_name='authsession',
            index=models.Index(fields=['user', 'revoked_at'], name='identity_auth_session_user_idx'),
        ),
        migrations.AddIndex(
            model_name='otpchallenge',
            index=models.Index(fields=['phone_hash', 'created_at'], name='identity_otp_phone_idx'),
        ),
        migrations.AddConstraint(
            model_name='otpchallenge',
            constraint=models.CheckConstraint(condition=models.Q(('attempts__lte', models.F('max_attempts'))), name='identity_otp_challenge_attempts_max_check'),
        ),
    ]
