# Generated by Django 5.2.18 on 2026-10-09 20:18

import django.contrib.postgres.fields
import django.db.models.deletion
import eduflow.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0004_enrollment_record_key'),
        ('tenancy', '0003_school_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=200)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('storage_key', models.CharField(help_text='Internal; never returned.', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
            ],
            options={
                'db_table': 'documents_stored_file',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, help_text='Free text, e.g. Certificates, Circulars.', max_length=60)),
                ('audiences', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('principal', 'Principal'), ('staff', 'Staff'), ('class_teacher', 'Class teacher'), ('teachers', 'Teachers'), ('parents', 'Parents'), ('students', 'Students'), ('accountant', 'Accountant')], max_length=16), default=list, size=None)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='people.staffprofile')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='people.student')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.storedfile')),
            ],
            options={
                'db_table': 'documents_document',
            },
        ),
        migrations.AddConstraint(
            model_name='storedfile',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='documents_stored_file_id_school_uniq'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['school', 'student'], name='documents_document_student_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('student__isnull', True), ('staff__isnull', True), _connector='OR'), name='documents_document_one_owner_check'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('audiences__contained_by', ['principal', 'staff', 'class_teacher', 'teachers', 'parents', 'students', 'accountant'])), name='documents_document_audiences_check'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='documents_document_id_school_uniq'),
        ),
    ]
