# Generated by Django 6.1.1 on 2026-09-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_homeworksubmission_checked_copy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksubmission',
            name='in_notebook',
            field=models.BooleanField(default=False),
        ),
    ]
