# Generated by Django 6.1.1 on 2026-09-26 10:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_remark_homework_remark_requires_ack_and_more'),
        ('attendance', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('kind', models.CharField(choices=[('sick', 'Sick'), ('family', 'Family'), ('other', 'Other')], default='sick', max_length=8)),
                ('reason', models.CharField(max_length=300)),
                ('half_day', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Waiting for the class teacher'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=8)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='academics.student')),
            ],
            options={
                'ordering': ['-from_date'],
            },
        ),
    ]
