# Generated by Django 6.1.1 on 2026-09-26 16:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def number_existing(apps, schema_editor):
    Correction = apps.get_model("attendance", "AttendanceCorrection")
    seen = {}
    for corr in Correction.objects.order_by("created_at"):
        seen[corr.school_id] = seen.get(corr.school_id, 400) + 1
        Correction.objects.filter(pk=corr.pk).update(number=seen[corr.school_id])


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_student_house'),
        ('attendance', '0003_attendancecorrection'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecorrection',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AbsenceContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('channel', models.CharField(choices=[('alert', 'Absence alert'), ('call', 'Phone call'), ('handoff', 'Handed to the front office')], max_length=8)),
                ('outcome', models.CharField(choices=[('sent', 'Sent'), ('reached', 'Reached'), ('no_answer', 'No answer')], default='sent', max_length=10)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_contacts', to='academics.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'date', 'channel'], name='attendance__school__285af7_idx')],
            },
        ),
        migrations.RunPython(number_existing, migrations.RunPython.noop),
    ]
