# Generated by Django 6.1.1 on 2026-09-26 15:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_student_house'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_no', models.CharField(max_length=30)),
                ('child_name', models.CharField(max_length=120)),
                ('grade', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('guardian_name', models.CharField(blank=True, max_length=120)),
                ('guardian_phone', models.CharField(blank=True, max_length=16)),
                ('documents_verified', models.BooleanField(default=False)),
                ('interaction_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('offered', 'Offer made'), ('declined', 'Declined')], default='applied', max_length=10)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
                ('sibling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
