# Generated by Django 6.1.1 on 2026-09-26 16:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def place_existing(apps, schema_editor):
    """Applications made before the board existed were waiting on the principal with documents checked."""
    Application = apps.get_model("admissions", "Application")
    Application.objects.filter(status="applied").update(stage="documents")
    Application.objects.filter(status="offered").update(stage="offer")
    Application.objects.filter(status="declined").update(stage="documents", closed=True, closed_reason="Not approved")


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_student_house'),
        ('admissions', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='admitted_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='assessment_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='assessment_out_of',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='application',
            name='assessment_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='closed_reason',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='application',
            name='documents_pending',
            field=models.CharField(blank=True, help_text='e.g. Report card, TC', max_length=80),
        ),
        migrations.AddField(
            model_name='application',
            name='enquired_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='fee_due_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='fee_receipt_no',
            field=models.CharField(blank=True, help_text='Admission-fee receipt the office issued', max_length=40),
        ),
        migrations.AddField(
            model_name='application',
            name='follow_up',
            field=models.CharField(blank=True, choices=[('', 'None'), ('call_back', 'Call back'), ('tour', 'School tour'), ('prospectus', 'Prospectus sent')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='application',
            name='follow_up_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='form_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_accepted_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_made_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_reply_by',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('walk_in', 'Walk-in'), ('referral', 'Referral'), ('social', 'Social media')], default='walk_in', max_length=10),
        ),
        migrations.AddField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('enquiry', 'Enquiry'), ('application', 'Application'), ('assessment', 'Assessment'), ('documents', 'Documents'), ('offer', 'Offer'), ('admitted', 'Admitted')], db_index=True, default='enquiry', max_length=12),
        ),
        migrations.AddField(
            model_name='application',
            name='stage_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission', to='academics.student'),
        ),
        migrations.CreateModel(
            name='AdmissionCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.CharField(max_length=20)),
                ('enquiries_open_on', models.DateField()),
                ('applications_close_on', models.DateField()),
                ('session_starts_on', models.DateField()),
                ('offer_rounds', models.JSONField(blank=True, default=list)),
                ('is_current', models.BooleanField(default=True)),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
            ],
            options={
                'ordering': ['-session_starts_on'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('created', 'Enquiry received'), ('moved', 'Moved'), ('assessment', 'Assessment booked'), ('scored', 'Assessment scored'), ('verified', 'Documents verified'), ('approved', 'Approved'), ('declined', 'Declined'), ('admitted', 'Admitted'), ('closed', 'Closed'), ('note', 'Note')], max_length=12)),
                ('from_stage', models.CharField(blank=True, max_length=12)),
                ('to_stage', models.CharField(blank=True, max_length=12)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='admissions.application')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeatPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=40)),
                ('grades', models.JSONField(default=list, help_text='Grades this row covers, e.g. ["2", "3", "4", "5"]')),
                ('seats', models.PositiveSmallIntegerField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_plans', to='admissions.admissioncycle')),
                ('school', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='admissioncycle',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year'), name='uniq_admission_cycle_year'),
        ),
        migrations.RunPython(place_existing, migrations.RunPython.noop),
    ]
