# Generated by Django 5.2.18 on 2026-10-10 08:02

import django.contrib.postgres.fields
import django.db.models.deletion
import eduflow.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_term_room_integrity_and_rls'),
        ('documents', '0002_tenant_integrity_and_rls'),
        ('people', '0004_enrollment_record_key'),
        ('tenancy', '0003_school_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_paths', to='academics.section')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.subject')),
            ],
            options={
                'db_table': 'lms_learning_path',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('chapter', models.CharField(blank=True, max_length=150)),
                ('kind', models.CharField(choices=[('video', 'Recorded video'), ('notes', 'Notes'), ('quiz', 'Quiz')], max_length=16)),
                ('body', models.TextField(blank=True, max_length=50000)),
                ('video_url', models.URLField(blank=True, max_length=500)),
                ('minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.storedfile')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_lessons', to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.subject')),
            ],
            options={
                'db_table': 'lms_lesson',
            },
        ),
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('starts_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('provider', models.CharField(help_text='Free text, e.g. the meeting service used.', max_length=40)),
                ('join_url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled')], default='scheduled', max_length=16)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='live_classes', to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.subject')),
            ],
            options={
                'db_table': 'lms_live_class',
            },
        ),
        migrations.CreateModel(
            name='LiveAttendance',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='people.student')),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='lms.liveclass')),
            ],
            options={
                'db_table': 'lms_live_attendance',
            },
        ),
        migrations.CreateModel(
            name='PathStep',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lms.lesson')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='lms.learningpath')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'lms_path_step',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('percent', models.PositiveSmallIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='lms.lesson')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_progress', to='people.student')),
            ],
            options={
                'db_table': 'lms_progress',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('max_attempts', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quizzes', to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.subject')),
            ],
            options={
                'db_table': 'lms_quiz',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('text', models.CharField(max_length=1000)),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), size=8)),
                ('answer', models.PositiveSmallIntegerField(help_text='Index of the correct option.')),
                ('explanation', models.CharField(blank=True, max_length=1000)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lms.quiz')),
            ],
            options={
                'db_table': 'lms_question',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='lms.quiz'),
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('answers', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), size=None)),
                ('score', models.PositiveSmallIntegerField()),
                ('total', models.PositiveSmallIntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz_attempts', to='people.student')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='lms.quiz')),
            ],
            options={
                'db_table': 'lms_attempt',
            },
        ),
        migrations.AddConstraint(
            model_name='learningpath',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='lms_learning_path_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='liveclass',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 1)), name='lms_live_duration_check'),
        ),
        migrations.AddConstraint(
            model_name='liveclass',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='lms_live_class_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='liveattendance',
            constraint=models.UniqueConstraint(fields=('live_class', 'student'), name='lms_live_attendance_uniq'),
        ),
        migrations.AddConstraint(
            model_name='liveattendance',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='lms_live_attendance_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pathstep',
            constraint=models.UniqueConstraint(fields=('path', 'position'), name='lms_step_position_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pathstep',
            constraint=models.UniqueConstraint(fields=('path', 'lesson'), name='lms_step_lesson_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pathstep',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='lms_path_step_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='progress',
            constraint=models.UniqueConstraint(fields=('lesson', 'student'), name='lms_progress_uniq'),
        ),
        migrations.AddConstraint(
            model_name='progress',
            constraint=models.CheckConstraint(condition=models.Q(('percent__lte', 100)), name='lms_progress_range_check'),
        ),
        migrations.AddConstraint(
            model_name='progress',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='lms_progress_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='lms_quiz_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('quiz', 'position'), name='lms_question_position_uniq'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='lms_question_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'video'), _negated=True), models.Q(('video_url', ''), _negated=True), _connector='OR'), name='lms_video_needs_url_check'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'quiz'), _negated=True), ('quiz__isnull', False), _connector='OR'), name='lms_quiz_lesson_check'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='lms_lesson_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.CheckConstraint(condition=models.Q(('score__lte', models.F('total'))), name='lms_attempt_score_le_total_check'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='lms_attempt_id_school_uniq'),
        ),
    ]
