# Generated by Django 5.2.18 on 2026-10-08 14:23

import django.contrib.postgres.fields
import django.db.models.deletion
import eduflow.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('codename', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('is_deprecated', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'authz_permission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(help_text='Stable machine key, unique within the school.', max_length=48)),
                ('name', models.CharField(max_length=100)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authz.role')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'authz_role',
            },
        ),
        migrations.CreateModel(
            name='MembershipRole',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='authz.role')),
            ],
            options={
                'db_table': 'authz_membership_role',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('scopes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('platform', 'Platform-wide'), ('school', 'Whole school'), ('campus', 'Own campus'), ('academic_year', 'Academic year'), ('department', 'Own department'), ('section', 'Assigned classes/sections'), ('assigned', 'Assigned students'), ('child', 'Own children'), ('self', 'Own record'), ('own', 'Records they created')], max_length=16), size=10)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='authz.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='authz.role')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
            ],
            options={
                'db_table': 'authz_role_permission',
            },
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('school', 'key'), name='authz_role_school_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='authz_role_id_school_uniq'),
        ),
        migrations.AddIndex(
            model_name='membershiprole',
            index=models.Index(fields=['school', 'membership'], name='authz_membership_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='membershiprole',
            constraint=models.UniqueConstraint(fields=('membership', 'role'), name='authz_membership_role_uniq'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['school', 'role'], name='authz_role_permission_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='authz_role_permission_uniq'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.CheckConstraint(condition=models.Q(('scopes__len__gt', 0)), name='authz_role_permission_scopes_check'),
        ),
    ]
