# Generated by Django 5.2.18 on 2026-10-10 05:56

import django.db.models.deletion
import eduflow.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_term_room_integrity_and_rls'),
        ('people', '0004_enrollment_record_key'),
        ('tenancy', '0003_school_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('occurred_on', models.DateField()),
                ('category', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=2000)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('serious', 'Serious')], max_length=16)),
                ('action_taken', models.CharField(blank=True, max_length=1000)),
                ('visible_to_family', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='people.student')),
            ],
            options={
                'db_table': 'conduct_incident',
                'indexes': [models.Index(fields=['school', 'occurred_on'], name='conduct_incident_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('severity__in', ['minor', 'moderate', 'serious'])), name='conduct_severity_check'), models.CheckConstraint(condition=models.Q(('status', 'open'), ('resolved_at__isnull', False), _connector='OR'), name='conduct_resolved_has_time_check'), models.UniqueConstraint(fields=('id', 'school'), name='conduct_incident_id_school_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tone', models.CharField(choices=[('praise', 'Praise'), ('concern', 'Concern'), ('note', 'Note')], max_length=16)),
                ('text', models.CharField(max_length=2000)),
                ('visible_to_family', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remarks', to='people.student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.subject')),
            ],
            options={
                'db_table': 'conduct_remark',
                'constraints': [models.CheckConstraint(condition=models.Q(('tone__in', ['praise', 'concern', 'note'])), name='conduct_remark_tone_check'), models.UniqueConstraint(fields=('id', 'school'), name='conduct_remark_id_school_uniq')],
            },
        ),
    ]
