# Generated by Django 5.2.18 on 2026-10-10 05:50

import django.db.models.deletion
import eduflow.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_term_room_integrity_and_rls'),
        ('documents', '0002_tenant_integrity_and_rls'),
        ('people', '0004_enrollment_record_key'),
        ('tenancy', '0003_school_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('assigned_on', models.DateField()),
                ('due_date', models.DateField()),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('archived', 'Archived')], default='published', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.storedfile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homework', to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='people.staffprofile')),
            ],
            options={
                'db_table': 'homework_homework',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=eduflow.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, max_length=10000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('late', 'Late'), ('reviewed', 'Reviewed')], max_length=16)),
                ('submitted_at', models.DateTimeField()),
                ('feedback', models.CharField(blank=True, max_length=2000)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.storedfile')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homework.homework')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homework_submissions', to='people.student')),
            ],
            options={
                'db_table': 'homework_submission',
            },
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['school', 'section', 'due_date'], name='homework_section_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='homework',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('assigned_on'))), name='homework_due_check'),
        ),
        migrations.AddConstraint(
            model_name='homework',
            constraint=models.CheckConstraint(condition=models.Q(('max_score__isnull', True), ('max_score__gt', 0), _connector='OR'), name='homework_max_score_check'),
        ),
        migrations.AddConstraint(
            model_name='homework',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['published', 'archived'])), name='homework_status_check'),
        ),
        migrations.AddConstraint(
            model_name='homework',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='homework_homework_id_school_uniq'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('homework', 'student'), name='homework_one_submission_uniq'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['submitted', 'late', 'reviewed'])), name='homework_submission_status_check'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'reviewed'), _negated=True), ('reviewed_at__isnull', False), _connector='OR'), name='homework_reviewed_has_time_check'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(condition=models.Q(('score__isnull', True), ('score__gte', 0), _connector='OR'), name='homework_score_check'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('id', 'school'), name='homework_submission_id_school_uniq'),
        ),
    ]
