# Generated by Django 6.1.1 on 2026-09-18 20:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('bus', 'Bus'), ('safety', 'Safety'), ('attendance', 'Attendance'), ('homework', 'Homework'), ('fees', 'Fees'), ('results', 'Results'), ('chat', 'Messages'), ('announcement', 'Announcements'), ('general', 'General')], default='general', max_length=16)),
                ('title', models.CharField(max_length=140)),
                ('body', models.CharField(max_length=500)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('dedupe_key', models.CharField(blank=True, max_length=200, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('push_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('quiet', 'Held for quiet hours'), ('skipped', 'Push disabled'), ('no_device', 'No device'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'school', '-created_at'], name='notif_user_school_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key__isnull', False)), fields=('user', 'dedupe_key'), name='uniq_notification_dedupe')],
            },
        ),
    ]
